# Generated by Django 3.1.6 on 2021-04-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientId', models.CharField(default=None, max_length=50)),
                ('qu', models.CharField(max_length=300)),
                ('du', models.CharField(max_length=300)),
                ('su', models.CharField(max_length=100)),
                ('sku1', models.CharField(max_length=100)),
                ('sku2', models.CharField(max_length=300)),
                ('pku1', models.CharField(max_length=300)),
                ('pku2', models.CharField(max_length=300)),
                ('socialaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
        ),
    ]
