# Generated by Django 3.1.6 on 2021-04-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='clientId',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
