# Generated by Django 3.1.6 on 2021-04-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0002_key_clientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='clientId',
        ),
    ]
