# Generated by Django 3.1.6 on 2021-04-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0004_key_clientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='sku1',
        ),
        migrations.RemoveField(
            model_name='key',
            name='sku2',
        ),
        migrations.RemoveField(
            model_name='key',
            name='su',
        ),
    ]
