# Generated by Django 3.1.6 on 2021-04-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0005_auto_20210409_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='words',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='cypherwords',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
