# Generated by Django 3.1.6 on 2021-04-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0006_auto_20210409_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='cypherwords',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
