# Generated by Django 3.1.6 on 2021-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0007_auto_20210409_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='pku1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='pku2',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
