# Generated by Django 3.1.6 on 2021-03-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('thesis', '0002_remove_senderkey_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiverkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sks', models.CharField(max_length=500)),
                ('pks', models.CharField(max_length=500)),
                ('socialaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
        ),
    ]
