# Generated by Django 3.1.6 on 2021-03-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0003_receiverkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverkey',
            name='clientsecrete',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='senderkey',
            name='clientsecrete',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
