# Generated by Django 3.1.6 on 2021-03-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_auto_20210330_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiverkey',
            name='clientsecrete',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='senderkey',
            name='clientsecrete',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
