# Generated by Django 3.1.6 on 2021-03-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_auto_20210330_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='data')),
                ('words', models.CharField(max_length=1000)),
            ],
        ),
    ]
