# Generated by Django 3.1.6 on 2021-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0007_auto_20210330_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='datafile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
