# Generated by Django 3.1.6 on 2021-04-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0008_auto_20210403_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='datafile',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
